### ISSUE TITLE
Importing Gorgeous Header

### ISSUE THREAD

**Issue by dhanushm360** [WrathChaos/react-native-gorgeous-header#1]
I am trying to import the Gorgeous Header into my typescript project. I've ran ‘npm i react-native-gorgeous-header’ and imported it into my project. However, it is giving me Cannot find module 'react-native-gorgeous-header' or its corresponding type declarations. I'm a bit of a beginner in Typescript, so step-by-step instructions would be highly appreciated. 

Thanks :)

**Comment by kuraydev** [comment]
Hello @dhanushm360,
I've tried the example but could not reproduce it. Can you share a reproducible example with me? Also, have you tried the example as well?

**Comment by dhanushm360** [comment]
Yes, I tried the example. I'm also using expo to run my project, does that make a difference?

**Comment by kuraydev** [comment]
Hello again @dhanushm360,
I added the example project: https://github.com/WrathChaos/react-native-gorgeous-header/tree/master/expo-example

It is working on expo as well, you only need to run `npm i` and `npm run start` it works great.

**Comment by dhanushm360** [comment]
Hi @WrathChaos,
Thanks for responding. I've tried importing this in a brand new typescript project with expo, but it wasn't working. In the import statement, there is an error saying: 

"Could not find a declaration file for module 'react-native-gorgeous-header'. 'C:/Users/Dhanush/headertest/node_modules/react-native-gorgeous-header/build/dist/GorgeousHeader.js' implicitly has an 'any' type. Try `npm i --save-dev @types/react-native-gorgeous-header` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-gorgeous-header';`"

I just fixed this by installing the latest version of tslib and now it works great. Thanks so much for your help and nice job on the awesome library!

**Comment by kuraydev** [comment]
@dhanushm360 
I just created a fresh project (in the expo-example folder), I just `npm i tslib && npm i react-native-gorgeous-header` and it works. I did not need to install `@types/react-native-gorgeous-header`. Maybe it is because of your local configuration.

I'm glad that it works for you :) 
Please feel free to contribute or open any issue :) 
Have fun
